version: '3'

services:
    php:
        build: docker/php
        image: php:8.1-fpm-alpine-httpclient-dev
        volumes:
            - ./:/http-client
        networks:
            - http-client-network
    apache:
        image: httpd:2.4-alpine
        ports:
            - 80:80
        volumes:
            - ./tests/System:/usr/local/apache2/htdocs/
            - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
        networks:
            - http-client-network
networks:
    http-client-network:
        driver: bridge
