version: '3'

services:
    php:
        build: docker/php
        image: php:7.2-fpm-alpine-dev
        volumes:
            - ./:/http-client
        networks:
            - http-client-network
    nginx:
        image: nginx:1-alpine
        ports:
            - 80:80
        volumes:
            - ./:/http-client
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - http-client-network
networks:
    http-client-network:
        driver: bridge
