name: "Continuous Integration"
on:
  pull_request:
  push:
    branches:
      - master
      - 1.x
jobs:
  phpunit-smoke-check:
    name: "PHPUnit"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.4"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--ignore-platform-req=php+"
          dependency-versions: "${{ matrix.dependencies }}"
      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit"
